-- your icon constants (could be loaded from elsewhere)
local ICON_TERM           = ""
local ICON_FILE           = ""
local ICON_WEATHER        = ""
local ICON_CLOCK          = ""
local ICON_MAIL           = ""
local ICON_CALENDAR       = ""
local ICON_CALC           = ""
local ICON_MAP            = ""
local ICON_MICROPHONE     = ""
local ICON_CHAT           = ""
local ICON_VIDEOCHAT      = ""
local ICON_NOTE           = ""
local ICON_LIST           = ""
local ICON_CAMERA         = ""
local ICON_WEB            = ""
local ICON_COG            = ""
local ICON_HOMEAUTOMATION = "󰘡"
local ICON_MUSIC          = ""
local ICON_PODCAST        = ""
local ICON_PLAY           = ""
local ICON_BOOK           = ""
local ICON_DEV            = ""
local ICON_GAME           = ""
local ICON_BOOKINFO       = ""
local ICON_CHART          = ""
local ICON_DISK           = ""
local ICON_PREVIEW        = ""
local ICON_PASSKEY        = ""
local ICON_VPN            = ""
local ICON_DOWNLOAD       = ""
local ICON_CAST           = ""
local ICON_TABLE          = ""
local ICON_PRESENT        = ""
local ICON_CLOUD          = ""
local ICON_PEN            = ""
local ICON_REMOTEDESKTOP  = ""
local ICON_APP            = ""  -- fallback

-- map app-name → icon
local appIcons = {
  ["kitty"]            = ICON_TERM,
  ["Warp"]                = ICON_TERM,
  ["iTerm2"]              = ICON_TERM,
  ["Finder"]              = ICON_FILE,
  ["Weather"]             = ICON_WEATHER,
  ["Clock"]               = ICON_CLOCK,
  ["Mail"]                = ICON_MAIL,
  ["Microsoft Outlook"]   = ICON_MAIL,
  ["Calendar"]            = ICON_CALENDAR,
  ["Calculator"]          = ICON_CALC,
  ["Numi"]                = ICON_CALC,
  ["Maps"]                = ICON_MAP,
  ["Find My"]             = ICON_MAP,
  ["Voice Memos"]         = ICON_MICROPHONE,
  ["Messages"]            = ICON_CHAT,
  ["Slack"]               = ICON_CHAT,
  ["Microsoft Teams"]     = ICON_CHAT,
  ["Discord"]             = ICON_CHAT,
  ["Telegram"]            = ICON_CHAT,
  ["FaceTime"]            = ICON_VIDEOCHAT,
  ["zoom.us"]             = ICON_VIDEOCHAT,
  ["Webex"]               = ICON_VIDEOCHAT,
  ["Notes"]               = ICON_NOTE,
  ["Zotero"]               = ICON_NOTE,
  ["Obsidian"]               = ICON_NOTE,
  ["TextEdit"]            = ICON_NOTE,
  ["Stickies"]            = ICON_NOTE,
  ["Microsoft Word"]      = ICON_NOTE,
  ["Reminders"]           = ICON_LIST,
  ["Microsoft OneNote"]   = ICON_LIST,
  ["Photo Booth"]         = ICON_CAMERA,
  ["Zen"]              = ICON_WEB,
  ["Safari"]              = ICON_WEB,
  ["Beam"]                = ICON_WEB,
  ["DuckDuckGo"]          = ICON_WEB,
  ["Arc"]                 = ICON_WEB,
  ["Microsoft Edge"]      = ICON_WEB,
  ["Google Chrome"]       = ICON_WEB,
  ["Firefox"]             = ICON_WEB,
  ["System Settings"]     = ICON_COG,
  ["System Information"]  = ICON_COG,
  ["TinkerTool"]          = ICON_COG,
  ["HOME"]                = ICON_HOMEAUTOMATION,
  ["Music"]               = ICON_MUSIC,
  ["Spotify"]             = ICON_MUSIC,
  ["Podcasts"]            = ICON_PODCAST,
  ["TV"]                  = ICON_PLAY,
  ["QuickTime Player"]    = ICON_PLAY,
  ["stremio"]              = ICON_PLAY,
  ["VLC"]                 = ICON_PLAY,
  ["Books"]               = ICON_BOOK,
  ["Xcode"]               = ICON_DEV,
  ["Code"]                = ICON_DEV,
  ["Neovide"]             = ICON_DEV,
  ["Font Book"]           = ICON_BOOKINFO,
  ["Dictionary"]          = ICON_BOOKINFO,
  ["Activity Monitor"]    = ICON_CHART,
  ["Disk Utility"]        = ICON_DISK,
  ["Screenshot"]          = ICON_PREVIEW,
  ["Preview"]             = ICON_BOOK,
  ["1Password"]           = ICON_PASSKEY,
  ["NordVPN"]             = ICON_VPN,
  ["Progressive Downloaded"] = ICON_DOWNLOAD,
  ["Transmission"]        = ICON_DOWNLOAD,
  ["Airflow"]             = ICON_CAST,
  ["Microsoft Excel"]     = ICON_TABLE,
  ["Microsoft PowerPoint"]= ICON_PRESENT,
  ["OneDrive"]            = ICON_CLOUD,
  ["Curve"]               = ICON_PEN,
  ["VMware Fusion"]       = ICON_REMOTEDESKTOP,
  ["UTM"]                 = ICON_REMOTEDESKTOP,
  ["Steam Helper"]        = ICON_GAME,
  ["iPhone Mirroring"]    = ICON_REMOTEDESKTOP,
  default                 = ICON_APP,  -- fallback
}

return appIcons