-- require("items.apple")
require("items.spaces_simple")
-- require("items.front_app")
require("items.layout")
-- require("items.separator")
require("items.apps")
require("items.lock")
require("items.settings")
require("items.calendar")
require("items.temp")
-- require("items.uname")
require("items.volume")
require("items.battery")
require("items.bus")
require("items.flow")
require("items.vpn")
require("items.input_source")
-- require("items.media")
-- require("items.upnext")
-- 