-- require("items.apple")
require("items.spaces")
-- require("items.front_app")
require("items.layout")
require("items.lock")
require("items.settings")
require("items.calendar")
-- require("items.uname")
require("items.volume")
require("items.battery")
require("items.bus")
require("items.temp")
require("items.flow")
require("items.media")
