#!/usr/bin/env lua

-- This is only needed once to install the sketchybar module
-- (or for an update of the module)
os.execute("[ ! -d $HOME/.local/share/sketchybar_lua/ ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)")

-- also need to install SwitchAudioSource

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"


-- Require the sketchybar module

sbar = require("sketchybar")
-- sbar.set_bar_name("bottom_bar")

-- Bundle the entire initial configuration into a single message to sketchybar
-- This improves startup times drastically, try removing both the begin and end
-- config calls to see the difference -- yeah..
sbar.begin_config()
require("init")
sbar.hotload(true)
sbar.end_config()

-- Run the event loop of the sketchybar module (without this there will be no
-- callback functions executed in the lua module)
sbar.event_loop()

-- {animate = function: 0x102a186b4, hotload = function: 0x102a1a8f8, default = function: 0x102a18cc8, bar = function: 0x102a18d98, add = function: 0x102a19f98, delay = function: 0x102a1b1b0, remove = function: 0x102a1a6ac, push = function: 0x102a19cf4, set = function: 0x102a18b74, update = function: 0x102a1a790, end_config = function: 0x102a18a50, trigger = function: 0x102a1aa18, subscribe = function: 0x102a195f8, exec = function: 0x102a1ac5c, set_bar_name = function: 0x102a1abbc, begin_config = function: 0x102a18900, query = function: 0x102a19814, event_loop = function: 0x102a1a790, }> 
-- > function dump(tbl) io.write("{") for k, v in pairs(tbl) do io.write(k .. " = ") if type(v) == "table" then dump(v) else io.write(tostring(v)) end io.write(", ") end io.write("}") end