#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# global settings
yabai -m config                                 \
    external_bar                 all:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_insertion_point       focused        \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12 \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   12             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


# manage=off some apps
# yabai -m rule --add app="^kitty$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Zoom$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off


# communcation discord messages slack always on space 4
yabai -m rule --add app="^Slack$" space=5
yabai -m rule --add app="^Messages$" space=5
yabai -m rule --add app="^Discord$" space=5
yabai -m rule --add app="^Mail$" space=5

yabai -m rule --add app="^Zen.*$" \
         role="AXLayoutArea" \
         subrole="AXFloatingWindow" \
         manage=off

# label the spaces "misc1 code1 code2 social write play script play misc2"
# yabai -m space 1 --label "misc1"
# yabai -m space 2 --label "code1"
# yabai -m space 3 --label "code2"
# yabai -m space 4 --label "social"
# yabai -m space 5 --label "write"
# yabai -m space 6 --label "play"
# yabai -m space 7 --label "script"
# yabai -m space 8 --label "play"
# yabai -m space 9 --label "misc2"
# events
## windows crud events, trigger to sketchybars custom event windows_changed
yabai -m signal --add event=window_created action="sketchybar  --trigger event_custom_windows_changed" 
yabai -m signal --add event=window_destroyed action="sketchybar  --trigger event_custom_windows_changed"
# yabai -m signal --add event=window_moved action="sketchybar  --trigger event_custom_windows_changed"
    
# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=7.0 &
echo "yabai configuration loaded.."
