#!/bin/bash

# ################################################################ #
# THE FOLLOWING IS AN EXPLANATION OF THE GRAMMAR THAT SKHD PARSES. #
# FOR SIMPLE EXAMPLE MAPPINGS LOOK FURTHER DOWN THIS FILE..        #
# ################################################################ #

# A list of all built-in modifier and literal keywords can
# be found at https://github.com/koekeishiya/skhd/issues/1
#
# A hotkey is written according to the following rules:
#
#   hotkey       = <mode> '<' <action> | <action>
#
#   mode         = 'name of mode' | <mode> ',' <mode>
#
#   action       = <keysym> '[' <proc_map_lst> ']' | <keysym> '->' '[' <proc_map_lst> ']'
#                  <keysym> ':' <command>          | <keysym> '->' ':' <command>
#                  <keysym> ';' <mode>             | <keysym> '->' ';' <mode>
#
#   keysym       = <mod> '-' <key> | <key>
#
#   mod          = 'modifier keyword' | <mod> '+' <mod>
#
#   key          = <literal> | <keycode>
#
#   literal      = 'single letter or built-in keyword'
#
#   keycode      = 'apple keyboard kVK_<Key> values (0x3C)'
#
#   proc_map_lst = * <proc_map>
#
#   proc_map     = <string> ':' <command> | <string>     '~' |
#                  '*'      ':' <command> | '*'          '~'
#
#   string       = '"' 'sequence of characters' '"'
#
#   command      = command is executed through '$SHELL -c' and
#                  follows valid shell syntax. if the $SHELL environment
#                  variable is not set, it will default to '/bin/bash'.
#                  when bash is used, the ';' delimeter can be specified
#                  to chain commands.
#
#                  to allow a command to extend into multiple lines,
#                  prepend '\' at the end of the previous line.
#
#                  an EOL character signifies the end of the bind.
#
#   ->           = keypress is not consumed by skhd
#
#   *            = matches every application not specified in <proc_map_lst>
#
#   ~            = application is unbound and keypress is forwarded per usual, when specified in a <proc_map>
#
# A mode is declared according to the following rules:
#
#   mode_decl = '::' <name> '@' ':' <command> | '::' <name> ':' <command> |
#               '::' <name> '@'               | '::' <name>
#
#   name      = desired name for this mode,
#
#   @         = capture keypresses regardless of being bound to an action
#
#   command   = command is executed through '$SHELL -c' and
#               follows valid shell syntax. if the $SHELL environment
#               variable is not set, it will default to '/bin/bash'.
#               when bash is used, the ';' delimeter can be specified
#               to chain commands.
#
#               to allow a command to extend into multiple lines,
#               prepend '\' at the end of the previous line.
#
#               an EOL character signifies the end of the bind.

# ############################################################### #
# THE FOLLOWING SECTION CONTAIN SIMPLE MAPPINGS DEMONSTRATING HOW #
# TO INTERACT WITH THE YABAI WM. THESE ARE SUPPOSED TO BE USED AS #
# A REFERENCE ONLY, WHEN MAKING YOUR OWN CONFIGURATION..          #
# ############################################################### #

# focus window
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east
alt - k : yabai -m window --focus north || yabai -m window --focus stack.prev || yabai -m window --focus stack.last
alt - j : yabai -m window --focus south || yabai -m window --focus stack.next || yabai -m window --focus stack.first

# focus monitor alt a alt s
alt - 0x2B : yabai -m display --focus prev
alt - 0x2F : yabai -m display --focus next

# swap managed window
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# change size of windows with j to decrease and k to increase
ctrl + alt - j : yabai -m window --resize right:-20:0
ctrl + alt - k : yabai -m window --resize right:20:0

# change layout by execute reset to default padding and  ./layout.sh
alt - tab:   sh ~/.config/skhd/layout.sh && \
             yabai -m space --padding abs:12:12:12:12 && 

# balance size of windows
alt - r : yabai -m space --balance # reset

# make floating window fill screen
# shift + alt - up     : yabai -m window --grid 1:1:0:0:1:1

# make floating window fill left-half of screen
# shift + alt - left   : yabai -m window --grid 1:2:0:0:1:1

# create desktop, move window and follow focus - uses jq for parsing json (brew install jq)
# shift + cmd - n : yabai -m space --create && \
#                   index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && \
#                   yabai -m window --space "${index}" && \
#                   yabai -m space --focus "${index}"

# fast focus desktop
alt - 0x32: yabai -m space --focus recent
alt - 0x1B: yabai -m space --focus recent
# alt - minus: yabai -m space --focus recent
# focus space 1-9
# alt - 1 call script focus.sh and pass 1 as argument
alt - 1 : sh ~/.config/skhd/focus.sh 1
alt - 2 : sh ~/.config/skhd/focus.sh 2
alt - 3 : sh ~/.config/skhd/focus.sh 3
alt - 4 : sh ~/.config/skhd/focus.sh 4
alt - 5 : sh ~/.config/skhd/focus.sh 5 
alt - 6 : sh ~/.config/skhd/focus.sh 6
alt - 7 : sh ~/.config/skhd/focus.sh 7
alt - 8 : sh ~/.config/skhd/focus.sh 8
alt - 9 : sh ~/.config/skhd/focus.sh 9
# alt - 1 : yabai -m space --focus 1
# alt - 2 : yabai -m space --focus 2
# alt - 3 : yabai -m space --focus 3
# alt - 4 : yabai -m space --focus 4
# alt - 5 : yabai -m space --focus 5
# alt - 6 : yabai -m space --focus 6
# alt - 7 : yabai -m space --focus 7
# alt - 8 : yabai -m space --focus 8
# alt - 9 : yabai -m space --focus 9



# send window to desktop

shift + alt - 1 : yabai -m window --space 1; sketchybar  --trigger event_custom_windows_changed
shift + alt - 2 : yabai -m window --space 2; sketchybar  --trigger event_custom_windows_changed
shift + alt - 3 : yabai -m window --space 3; sketchybar  --trigger event_custom_windows_changed
shift + alt - 4 : yabai -m window --space 4; sketchybar  --trigger event_custom_windows_changed
shift + alt - 5 : yabai -m window --space 5; sketchybar  --trigger event_custom_windows_changed
shift + alt - 6 : yabai -m window --space 6; sketchybar  --trigger event_custom_windows_changed
shift + alt - 7 : yabai -m window --space 7; sketchybar  --trigger event_custom_windows_changed
shift + alt - 8 : yabai -m window --space 8; sketchybar  --trigger event_custom_windows_changed
shift + alt - 9 : yabai -m window --space 9; sketchybar  --trigger event_custom_windows_changed
shift + alt - 0 : yabai -m window --space 10; sketchybar  --trigger event_custom_windows_changed

# focus monitor

# send window to monitor and follow focus
# ctrl + cmd - c  : yabai -m window --display next; yabai -m display --focus next
# ctrl + cmd - 1  : yabai -m window --display 1; yabai -m display --focus 1

# move floating window
# shift + ctrl - a : yabai -m window --move rel:-20:0
# shift + ctrl - s : yabai -m window --move rel:0:20

# increase window size
shift + alt - a : yabai -m window --resize left:-20:0
shift + alt - w : yabai -m window --resize top:0:-20

# decrease window size
shift + cmd - s : yabai -m window --resize bottom:0:-20
shift + cmd - w : yabai -m window --resize top:0:20

# set insertion point in focused container
# ctrl + alt - h : yabai -m window --insert west

# toggle window zoom
# alt - d : yabai -m window --toggle zoom-parent
# alt - f : yabai -m window --toggle zoom-fullscreen

# toggle window split type
# alt - e : yabai -m window --toggle split

# float / unfloat window and center on screen
alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2

# focus mode by enter stack and yabai -m space --padding abs:250:250:250:250
alt - v :   yabai -m space --layout stack  && \
            yabai -m space --padding abs:100:100:100:100 && \
            sketchybar --trigger event_custom_layout_changed
            # yabai -m space --balance

# toggle sticky(+float), picture-in-picture
# alt - p : yabai -m window --toggle sticky --toggle pip


# shortcut to fast open apps
# kitty
alt - return : /opt/homebrew/bin/kitty --single-instance
alt - b : /Applications/Zen.app/Contents/MacOS/zen

#alt -space to run cmd+space

alt - space: skhd -k "cmd - space"
alt - w: skhd -k "cmd - w"
# cmd - x: skhd -k "cmd - w"

# reload yabai config
# ctrl + alt - q : yabai --restart-service ; sketchybar --reload
ctrl + alt - q : sketchybar --reload; toptop_bar --reload


# alt - a : sh ~/.config/skhd/focus_window.sh 1
# alt - s : sh ~/.config/skhd/focus_window.sh 2
alt - a : sh ~/.config/skhd/focus_window.sh 1
alt - s : sh ~/.config/skhd/focus_window.sh 2
alt - d : sh ~/.config/skhd/focus_window.sh 3
alt - f : sh ~/.config/skhd/focus_window.sh 4
# alt - g : sh ~/.config/skhd/focus_window.sh 5
# alt - h : sh ~/.config/skhd/focus_window.sh 6

alt - q : $HOME/.config/skhd/kill_last_instance.sh
alt - x : $HOME/.config/skhd/kill_last_instance.sh

# prevents skhd from monitoring events for listed processes.
.blacklist [
    "UTM"
]